baseURL = "https://gohugo-theme-ananke.pages.dev"
theme = "ananke"
resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = 'G-60M36FW674'

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "Ottawa Queer Haven Project"
# languageDirection = 'rtl' for Right-To-Left languages

# [languages.fr]
# contentDir = "content/fr"
# languageCode = 'fr-FR'
# weight = 2
# title = "Projet Queer Haven d'Ottawa"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = "black"
read_more_copy = "Click to read more"
author = "613 Queer Haven"
favicon = ""
# site_logo = "images/"
description = "Ottawa Community Support and Action"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-light-green"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-center"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-white-20"
recent_posts_number = 1
custom_css = ["custom.css"]
emailAddress = "test@mail.com"
body_classes = "avenir bg-near-white"

[markup.goldmark.renderer]
unsafe = true #to enable html directly in markdown

[params.ananke.social.share]
networks = [
  "email"
]

[params]
  featured_image_alt = "A rainbow pride flag waving against a bright blue sky, symbolizing LGBTQ+ rights and inclusivity"
  image_credit = "Photo by Rob Maxwell on Unsplash"

